var button={
	button:null,
	constant: {
		icon:{path:'icons/fler_18.png'},
		iconOff:{path:'icons/fler_18-gray.png'},
		badgeTop:{color:[255,0,0,255]},
		badgeLoad:{color:[100,100,100,50]},
		badgeWait:{color:[0,0,255,255]},
                labels:Array(
			chrome.i18n.getMessage("time_measure_s"),
			chrome.i18n.getMessage("time_measure_m"),
			chrome.i18n.getMessage("time_measure_h"),
			chrome.i18n.getMessage("time_measure_d")
			)
	},
	init:function(){
		chrome.browserAction.setIcon(this.constant.iconOff);
		chrome.browserAction.setBadgeBackgroundColor(this.constant.badgeLoad);
		chrome.browserAction.setTitle({title:chrome.i18n.getMessage("starting")});
		chrome.browserAction.setBadgeText({text:""});
	},
	changeState:function(state){
		state();
		this.update();
	},
	update:function(){
		this.onUpdate();
	},
	onUpdate:function(){},
	state:{
		loading:function(){
			chrome.browserAction.setIcon(button.constant.iconOff);
			chrome.browserAction.setBadgeBackgroundColor(button.constant.badgeLoad);
			chrome.browserAction.setTitle({title:chrome.i18n.getMessage("loading")});
			chrome.browserAction.setBadgeText({text:"…"});
			button.onUpdate=function(){};		
		},
		waiting:function(){
			chrome.browserAction.setIcon(button.constant.icon);
			chrome.browserAction.setBadgeBackgroundColor(button.constant.badgeWait);
			chrome.browserAction.setTitle({title:chrome.i18n.getMessage("next")+"\n\t"
				+time.getDateString()+" \n\t"
				+time.getTimeString()});
			button.onUpdate=function(){
				chrome.browserAction.setBadgeText({text:time.getLeftString(button.constant.labels)});
			};
		},
		working:function(){
			chrome.browserAction.setIcon(button.constant.icon);
			chrome.browserAction.setBadgeBackgroundColor(button.constant.badgeTop);
			chrome.browserAction.setTitle({title:chrome.i18n.getMessage("top")});
			chrome.browserAction.setBadgeText({text:"top"});
			button.onUpdate=function(){};
		},
		offline:function(){
			chrome.browserAction.setIcon(button.constant.iconOff);
			chrome.browserAction.setBadgeBackgroundColor(button.constant.badgeLoad);
			chrome.browserAction.setTitle({title:chrome.i18n.getMessage("offline")+"\n\t"
				+chrome.i18n.getMessage("offline_help")});
			chrome.browserAction.setBadgeText({text:""});
			button.onUpdate=function(){};
		},
	},
};
